provider:
  name: faas
  gateway: https://faas.srv.locational.io
functions:
  longrun:
    lang: node
    handler: ./longrun
    image: onlyjsmith/longrun:0.0.5
    write_timeout: 57
    read_timeout: 57
    exec_timeout: 60
    write_debug: true
    combine_output: false
