name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - uses: LucasRoesler/openfaas-action/template_store_pull@master
      name: Fetch Template
      with:
        name: "dockerfile"
    - uses: LucasRoesler/openfaas-action/build@master
      name: Build
      with:
        path: "stack.yml"
        tag: "sha"
    - uses: LucasRoesler/openfaas-action/push@master
      name: Push image
      if: "success() && github.ref == 'refs/heads/master' "
      with:
        path: "stack.yml"
        tag: "sha"
